### ISSUE TITLE
Missing workflow file

### ISSUE THREAD

**Issue by rhsev** [FireFingers21/alfred-linkding-bookmarks#1]
Looks like an interesting workflow for Alfred. However, there is no workflow file. Can you please provide it?

**Comment by FireFingers21** [comment]
Thanks for your interest! The workflow is available to download as a [Release](https://docs.github.com/en/repositories/releasing-projects-on-github/viewing-your-repositorys-releases-and-tags). You'll find the `.alfredworkflow` file in the latest release [here](https://github.com/FireFingers21/alfred-linkding-bookmarks/releases/latest).

**Comment by rhsev** [comment]
Oh man 🤦‍♂️ Thank you. Workflow works very well.
