### ISSUE TITLE
Encountered a jq error

### ISSUE THREAD

**Issue by llity** [FireFingers21/alfred-linkding-bookmarks#2]
![image](https://github.com/user-attachments/assets/0fc8a3e3-c39f-478f-bc10-c00595ed4a67)

ERROR: linkding Bookmarks[Script Filter] Code 5: jq: parse error: Invalid numeric literal at line 2, column 10

**Comment by FireFingers21** [comment]
Are you using the latest version of the workflow? It's available on the [Alfred Gallery](https://alfred.app/workflows/firefingers21/linkding-bookmarks/).

Also how far into using the workflow did you get before getting the error?

**Comment by FireFingers21** [comment]
Also try manually reloading the bookmark cache with the `bm::` keyword, as shown in the third image of the README. The workflow caches all data pulled from the linkding API into a single line of a JSON file, so I'm not sure why you're getting a parse error on line 2.

You can find the cache file at `~/Library/Application Support/Alfred/Workflow Data/com.firefingers21.linkdingbookmarks/bookmarks.json`. If updating the workflow and reloading the bookmark cache doesn't work, I'd be curious to see if anything is wrong in that file.

**Comment by llity** [comment]
I reconfigured it with a different computer and it's working perfectly now. Thanks!
