### ISSUE TITLE
bm keyword not searching bookmarks

### ISSUE THREAD

**Issue by keybits** [FireFingers21/alfred-linkding-bookmarks#3]
Hi, thank you for making this - just what I was looking for!

I just installed from the Alfred Gallery and set base url and api key. It successfully loads bookmark cache with `bm::` but if I type `bm my search term` I just get a web search:

<img width="717" alt="image" src="https://github.com/user-attachments/assets/b14fd3cb-2c60-466c-a38d-7fc13aa7bee5">

Any suggestion on why it's not working? I haven't changed anything else other than mentioned above from the default install.

**Comment by keybits** [comment]
oops - just realised I had a trailing slash on my base url... 🤦

**Comment by FireFingers21** [comment]
All good lol, glad you're enjoying the workflow!
